/**
 * Security + indexability headers for Pages FUNCTION responses.
 *
 * Cloudflare Pages applies _headers ONLY to static asset responses — never to a
 * response generated by a Function. So /, /categories and /product/<sku> (all
 * Function-rendered now) were shipping with none of the CSP / HSTS / X-Frame /
 * Referrer / Permissions / X-Robots headers that every static page inherits from
 * _headers. This module restores exactly that set on the Function responses.
 *
 * KEEP IN SYNC with the `/*` security block and the public-page X-Robots lines
 * in the root _headers file. The CSP here is a verbatim copy of the one there.
 */
export const SECURITY_HEADERS = {
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'SAMEORIGIN',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  'Permissions-Policy':
    'camera=(), microphone=(), geolocation=(), payment=(self "https://checkout.razorpay.com"), ' +
    'usb=(), magnetometer=(), gyroscope=(), accelerometer=(), fullscreen=(self), interest-cohort=()',
  'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload',
  'Cross-Origin-Opener-Policy': 'same-origin-allow-popups',
  'X-XSS-Protection': '1; mode=block',
  'X-DNS-Prefetch-Control': 'on',
  'Content-Security-Policy':
    "default-src 'self'; " +
    "script-src 'self' 'unsafe-inline' https://*.razorpay.com https://www.googletagmanager.com https://*.google-analytics.com https://*.gstatic.com https://*.google.com https://challenges.cloudflare.com; " +
    "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://*.gstatic.com; " +
    "font-src 'self' https://fonts.gstatic.com; " +
    "img-src 'self' data: blob: https:; " +
    "connect-src 'self' https://*.razorpay.com https://*.googleapis.com https://api.postalpincode.in https://*.google-analytics.com https://www.googletagmanager.com https://*.gstatic.com https://*.google.com https://challenges.cloudflare.com; " +
    "frame-src https://*.razorpay.com https://*.google.com https://challenges.cloudflare.com; " +
    "object-src 'none'; base-uri 'self'; form-action 'self' https://*.razorpay.com; frame-ancestors 'self'",
  // Positive robots tag every indexable Function page (/, /categories, /product/*)
  // used to get from _headers. Absence still means indexable, but this restores
  // the rich-result preview directives.
  'X-Robots-Tag': 'index, follow, max-image-preview:large, max-snippet:-1',
};
